Repository eclipse-hawkbit/hawkbit, pull requests merged in 2020-10, with the labels that each got.

#1019 Note added for using MariaDB 10.1 on Ubuntu
  docs/content/guides/runhawkbit.md
Labels: documentation

#1022 Deregister UI remote event push strategy from application context
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/AbstractHawkbitUI.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/push/DelayedEventBusPushStrategy.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/utils/SpringContextHelper.java
  hawkbit-ui/src/main/resources/hawkbit-ui-defaults.properties
Labels: bug

#1033 Added docker auth to circle-CI
  .circleci/config.yml
Labels: task

#1034 Feature docker auth
  .circleci/config.yml
Labels: task

#1035 Metadata UI permissions
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/artifacts/smtable/SmMetaDataAddUpdateWindowLayout.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/artifacts/smtable/SmMetaDataWindowLayout.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/detailslayout/AbstractMetaDataWindowLayout.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/detailslayout/DistributionSetDetailsHeader.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/detailslayout/MetaDataAddUpdateWindowLayout.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/detailslayout/MetaDataWindowGrid.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/detailslayout/MetadataDetailsGrid.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/detailslayout/MetadataWindowGridHeader.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/detailslayout/SoftwareModuleDetailsHeader.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/grid/header/AbstractDetailsHeader.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/grid/header/support/AddHeaderSupport.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/distributions/dstable/DsMetaDataWindowLayout.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/management/targettable/TargetDetails.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/management/targettable/TargetMetaDataWindowLayout.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/utils/UIComponentIdProvider.java
Labels: bug

#1037 JDK 11 build support for hawkBit
  pom.xml
Labels: CQ, enhancement

#1038 Java 11 support for hawkBit
  hawkbit-repository/hawkbit-repository-jpa/pom.xml
  hawkbit-repository/hawkbit-repository-jpa/src/main/java/org/eclipse/hawkbit/repository/jpa/model/JpaTarget.java
  pom.xml
Labels: CQ, task
