Repository eclipse-hawkbit/hawkbit, pull requests merged in 2021-02, with the labels that each got.

#1073 Add license header example to the contribution guide
  CONTRIBUTING.md
Labels: task

#1077 Fix NPE that occurs on invalid user input in editfields
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/data/proxies/ProxyIdentifiableEntity.java
Labels: bug

#1076 Permission matrix updated
  docs/content/concepts/authorization.md
Labels: documentation

#1079 Document and explain DB migration issue
  MIGRATION.md
Labels: documentation

#1078 Update .adoc path reference
  hawkbit-rest/hawkbit-rest-docs/src/main/asciidoc/targetfilters-api-guide.adoc
Labels: documentation

#1056 Show Controller ID within target, filter and rollouts view
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/builder/GridComponentBuilder.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/filtermanagement/TargetFilterTargetGrid.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/management/targettable/TargetGrid.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/rollout/rolloutgrouptargets/RolloutGroupTargetGrid.java
  hawkbit-ui/src/main/resources/messages.properties
Labels: enhancement

#1043 Restructure Tenant Configuration View to make it more flexible for adaptations
  hawkbit-dmf/hawkbit-dmf-amqp/src/main/java/org/eclipse/hawkbit/amqp/AmqpConfiguration.java
  hawkbit-dmf/hawkbit-dmf-amqp/src/main/java/org/eclipse/hawkbit/amqp/AmqpMessageDispatcherService.java
  hawkbit-dmf/hawkbit-dmf-amqp/src/test/java/org/eclipse/hawkbit/amqp/AmqpMessageDispatcherServiceTest.java
  hawkbit-dmf/hawkbit-dmf-amqp/src/test/java/org/eclipse/hawkbit/integration/AbstractAmqpServiceIntegrationTest.java
  hawkbit-dmf/hawkbit-dmf-amqp/src/test/java/org/eclipse/hawkbit/integration/AmqpMessageDispatcherServiceIntegrationTest.java
  hawkbit-dmf/hawkbit-dmf-amqp/src/test/java/org/eclipse/hawkbit/integration/AmqpMessageHandlerServiceIntegrationTest.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/data/proxies/ProxySystemConfigAuthentication.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/data/proxies/ProxySystemConfigDsType.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/data/proxies/ProxySystemConfigPolling.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/data/proxies/ProxySystemConfigRepository.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/data/proxies/ProxySystemConfigRollout.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/data/proxies/ProxySystemConfigWindow.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/tenantconfiguration/AuthenticationConfigurationView.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/tenantconfiguration/BaseConfigurationView.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/tenantconfiguration/DefaultDistributionSetTypeView.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/tenantconfiguration/PollingConfigurationView.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/tenantconfiguration/RepositoryConfigurationView.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/tenantconfiguration/RolloutConfigurationView.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/tenantconfiguration/SystemConfigViewAutoConfiguration.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/tenantconfiguration/TenantConfigurationDashboardView.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/tenantconfiguration/authentication/CertificateAuthenticationConfigurationItem.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/tenantconfiguration/authentication/GatewaySecurityTokenAuthenticationConfigurationItem.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/tenantconfiguration/repository/ActionAutoCleanupConfigurationItem.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/tenantconfiguration/repository/MultiAssignmentsConfigurationItem.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/tenantconfiguration/window/SystemConfigWindowLayoutComponentBuilder.java
Labels: refactoring

#1063 JUnit5 support
  hawkbit-artifact-repository-filesystem/pom.xml
  hawkbit-core/pom.xml
  hawkbit-core/src/test/java/org/eclipse/hawkbit/api/Base62UtilTest.java
  hawkbit-core/src/test/java/org/eclipse/hawkbit/api/PropertyBasedArtifactUrlHandlerTest.java
  hawkbit-dmf/hawkbit-dmf-amqp/pom.xml
  hawkbit-http-security/pom.xml
  hawkbit-repository/hawkbit-repository-api/pom.xml
  hawkbit-repository/hawkbit-repository-core/pom.xml
  hawkbit-repository/hawkbit-repository-jpa/pom.xml
  hawkbit-rest/hawkbit-ddi-api/pom.xml
  hawkbit-rest/hawkbit-ddi-resource/pom.xml
  hawkbit-rest/hawkbit-mgmt-api/pom.xml
  hawkbit-rest/hawkbit-mgmt-resource/pom.xml
  hawkbit-rest/hawkbit-rest-core/pom.xml
  hawkbit-rest/hawkbit-rest-docs/pom.xml
  hawkbit-runtime/hawkbit-update-server/pom.xml
  hawkbit-security-core/pom.xml
  hawkbit-security-integration/pom.xml
  hawkbit-ui/pom.xml
  pom.xml
Labels: task

#1089 Upgrade Vaadin to 8.12.3
  pom.xml
Labels: CQ, enhancement
