Repository eclipse-hawkbit/hawkbit, pull requests merged in 2021-01, with the labels that each got.

#1054 Add Github actions stale and first-interaction workflow
  .github/config.yml
  .github/no-response.yml
  .github/workflows/first-interaction.yml
  .github/workflows/stale.yml
Labels: task

#1064 Add existsByInstalledOrAssignedDistributionSet
  hawkbit-repository/hawkbit-repository-api/src/main/java/org/eclipse/hawkbit/repository/TargetManagement.java
  hawkbit-repository/hawkbit-repository-jpa/src/main/java/org/eclipse/hawkbit/repository/jpa/JpaTargetManagement.java
  hawkbit-repository/hawkbit-repository-jpa/src/main/java/org/eclipse/hawkbit/repository/jpa/TargetRepository.java
  hawkbit-repository/hawkbit-repository-jpa/src/test/java/org/eclipse/hawkbit/repository/jpa/TargetManagementTest.java
  hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/grid/support/assignment/SwModulesToDistributionSetAssignmentSupport.java
Labels: enhancement

#1042 Fixup force delete action documentation
  hawkbit-rest/hawkbit-rest-docs/src/main/asciidoc/targets-api-guide.adoc
  hawkbit-rest/hawkbit-rest-docs/src/test/java/org/eclipse/hawkbit/rest/mgmt/documentation/TargetResourceDocumentationTest.java
Labels: documentation

#1072 README: link to hawkbit-rs
  README.md
Labels: documentation

#1074 Do not accept valid token headers by default
  hawkbit-runtime/hawkbit-update-server/src/main/resources/application.properties
Labels: bug
